### ISSUE TITLE
typo on readme

### ISSUE THREAD

**Issue by hampsterx** [arqex/flux-reactions#2]
Hi Javier,

Readme states (2x)

```
React.createClass({
  mixin:[Reactions.mixin],
```

Should be "mixins".

Hehe, confused me for 5 minutes as to why "trigger" was undefined, lol 

Will reply to your comment (thnx btw) on freezer.js after I gather some thoughts on the matter, form rendering is something close to my heart :)

Cheers, TiM

**Comment by arqex** [comment]
Fixed, thanks!
